### ISSUE TITLE
SDK interface clarification

### ISSUE THREAD

**Issue by grausof** [italia/eudi-wallet-it-pid-provider-android-sdk#1]
We are analyzing the SDK together with @hevelius and @LazyAfternoons and we are experiencing some glitches in the interface.

In particular, it is not clear to us why within the demo app for the initialization of the SDK it is also necessary to pass the private key. This specification conflicts with the ARF and the need to use a TEE for signature.
I would have expected the SDK to provide one interface for getting stuff to sign and a second interface for sending the signed stuff.

Signing and key management in particular cannot be delegated to the SDK.

https://github.com/italia/eidas-it-wallet-pid-provider-android-sdk/blob/d46c3568b4e88f1985b2e75028d3e7d7d0319d3d/androidpidproviderdemo/src/main/java/it/ipzs/androidpidproviderdemo/PidProviderDemoApplication.kt#L49

Another point is the use of only `ECPublicKey` for the keys. It is necessary to be able to use `JWK` both RSA and EC as some android devices do not support EC.

Furthermore, we do not understand the need to have a wallet uri since it is already present in the Wallet Instance Attestation (iss).

**Comment by sviluppo-ipzs** [comment]
Hi Francesco,
Thanks for the support, but it does seem to us that all android devices support EC. From the documentation it can be seen that they are available starting from api level 1. 

https://developer.android.com/reference/java/security/spec/EllipticCurve

We choose EC because is able to provide more cryptographic strength than RSA.

We require them as an input parameter to prevent the SDK from managing them and create an api to request them. The SDK need it for DPoP generation keys for the PKCE flow.

**Comment by fventola-ipzs** [comment]
Fixed in version 1.1.1.
